version: '3.7'
services:
    teste_vaibem_db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: T3ST3V@1B3M

    teste_vaibem_api:
      container_name: teste_vaibem_api
      build:
        context: .
      restart: always
      volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
      ports:
        - 3333:3333
      env_file:
        - .env
      command: npm run start:dev
      depends_on:
        - teste_vaibem_db
      network: api